### ISSUE TITLE
Unable to load model in WavefrontObjDemo

### ISSUE THREAD

**Issue by red-hara** [LWJGL/lwjgl3-demos#19]
Hello. WavefrontObjDemo fails to run due to file loading error. (/home/hara/java_dev/ is the directory containing clone of 7fc7dd488805d4e08070b0116384d3d0ffed0589).
```
Move the mouse to look around
Zoom in/out with mouse wheel
java.lang.IllegalStateException: Unable to open file "/home/hara/java_dev/lwjgl3-demos/file:/home/hara/java_dev/lwjgl3-demos/target/lwjgl3-demos.jar!/org/lwjgl/demo/opengl/assimp/magnet.obj".
	at org.lwjgl.demo.opengl.assimp.WavefrontObjDemo.loadModel(WavefrontObjDemo.java:194)
	at org.lwjgl.demo.opengl.assimp.WavefrontObjDemo.init(WavefrontObjDemo.java:183)
	at org.lwjgl.demo.opengl.assimp.WavefrontObjDemo.run(WavefrontObjDemo.java:303)
	at org.lwjgl.demo.opengl.assimp.WavefrontObjDemo.main(WavefrontObjDemo.java:322)
```
Build and run steps:
```
$ mvn package -Dclass=opengl.assimp.WavefrontObjDemo
$ java -jar target/lwjgl3-demos.jar
```

```
$ cat /etc/os-release
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
ID_LIKE=archlinux
ANSI_COLOR="0;36"
HOME_URL="https://www.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
```
```
$ java -version
openjdk version "1.8.0_172"
OpenJDK Runtime Environment (build 1.8.0_172-b11)
OpenJDK 64-Bit Server VM (build 25.172-b11, mixed mode)
```

**Comment by httpdigest** [comment]
Thanks for the info! This is fixed now with the latest HEAD.

**Comment by red-hara** [comment]
Thank you.
Now it works perfectly.
