### ISSUE TITLE
Vulkan demo fails to create image

### ISSUE THREAD

**Issue by elogent** [LWJGL/lwjgl3-demos#2]
I am using the NVIDIA 364.19 driver on an NVIDIA GeForce GT 750M in Ubuntu 16.04 LTS. I was able to build the demo suite just fine:

```sh
git clone https://github.com/LWJGL/lwjgl3-demos.git
cd lwjgl3-demos
mvn package
```

The `SpaceGame` demo runs without any problems:

```sh
java -jar target/lwjgl3-demos.jar
```

However, when I try to run one of the Vulkan demos:

```sh
java -cp target/lwjgl3-demos.jar org.lwjgl.demo.vulkan.ClearScreenDemo
```

A window titled "GLFW Vulkan Demo" appears for a split second, then the demo crashes with this error:

```
ERROR OCCURED: vkCreateImage: image creation failed due to invalid parameter
Exception in thread "main" java.lang.AssertionError: Failed to create swap chain: A validation layer found an error.
	at org.lwjgl.demo.vulkan.ClearScreenDemo.createSwapChain(ClearScreenDemo.java:502)
	at org.lwjgl.demo.vulkan.ClearScreenDemo.access$400(ClearScreenDemo.java:62)
	at org.lwjgl.demo.vulkan.ClearScreenDemo$1SwapchainRecreator.recreate(ClearScreenDemo.java:916)
	at org.lwjgl.demo.vulkan.ClearScreenDemo.main(ClearScreenDemo.java:997)
```

Is this a bug, or have I just not properly configured my system to use Vulkan?

**Comment by httpdigest** [comment]
Sadly, I do not have a native Linux system to test this. All I can say is that with the latest 364.91 Nvidia driver it works without any errors and warnings on Windows 7 x64, also when having the latest LunarG SDK 1.0.11.0 installed and enabling the validation layer (via the `private static final boolean validation` field; disabled by default).
Did you enable that field and/or installed the LunarG SDK?

**Comment by httpdigest** [comment]
I just made a change to the demos. Can you please pull in the changes and test again?
If the error still persists, can you probably debug the demo and tell the values of some critical locals in the `createSwapChain` method, such as `colorFormat`, `colorSpace`, `preTransform`, `swapchainPresentMode`, `desiredNumberOfSwapchainImages` and `oldSwapChain` before the failed call to `vkCreateSwapchainKHR`?
Was there a call to `vkCreateSwapchainKHR` that succeeded before the failing one? And if so, which parameters did that call have?

**Comment by elogent** [comment]
That seems to have partially fixed the problem. Now when I run `ClearScreenDemo`, `ColoredRotatingQuadDemo`, `ColoredTriangleDemo`, or `TriangleDemo`, a black-filled window titled "GLFW Vulkan Demo" appears with no error. I can move the window around on the screen and close it without issue. When I resize the window, the black fill is replaced by the appropriate figure (nothing, colored rotating quad, colored triangle, or blue triangle, respectively) on a light blue background. I am able to expand the window as much as I want. However, when I make the window *smaller* in any dimension, I get this error:

```
Exception in thread "main" java.lang.AssertionError: Failed to submit command buffer: The logical or physical device has been lost.
	at org.lwjgl.demo.vulkan.ClearScreenDemo.submitCommandBuffer(ClearScreenDemo.java:670)
	at org.lwjgl.demo.vulkan.ClearScreenDemo.submitPostPresentBarrier(ClearScreenDemo.java:844)
	at org.lwjgl.demo.vulkan.ClearScreenDemo.main(ClearScreenDemo.java:1055)
```

The error doesn't appear every time I contract the window, though; I am usually able to contract it by some amount between a few pixels and a few hundred pixels before it crashes.

When I run `InstancedSpheresDemo`, `TwoRotatingTrianglesDemo`, or `TwoRotatingTrianglesInvDepthDemo`, I get the same window flash as before, but with a different error message:

```
ERROR OCCURED: vkCreateImage: image creation failed due to invalid parameter
Exception in thread "main" java.lang.AssertionError: Failed to create depth-stencil image: A validation layer found an error.
	at org.lwjgl.demo.vulkan.InstancedSpheresDemo.createDepthStencil(InstancedSpheresDemo.java:680)
	at org.lwjgl.demo.vulkan.InstancedSpheresDemo.access$1200(InstancedSpheresDemo.java:97)
	at org.lwjgl.demo.vulkan.InstancedSpheresDemo$1SwapchainRecreator.recreate(InstancedSpheresDemo.java:1581)
	at org.lwjgl.demo.vulkan.InstancedSpheresDemo.main(InstancedSpheresDemo.java:1664)
```

**Comment by httpdigest** [comment]
Do you have a Retina/HiDPI display? I'm just wildly guessing here, also with the commits. It seems your issues are related to the window width/height.
Could you please also checkout the [HelloVulkan](https://github.com/LWJGL/lwjgl3/blob/master/modules/core/src/test/java/org/lwjgl/demo/vulkan/HelloVulkan.java) demo in the [lwjgl3](https://github.com/LWJGL/lwjgl3) repository?

**Comment by elogent** [comment]
No, I'm using a 17" 1080p display. 38797aafcfa7b3275c6bace6b8259b202444874a fixed the problem for me, though. Thanks so much for your help! Do you still want me to try the `HelloVulkan` demo? If so, how exactly should I go about doing that?

**Comment by httpdigest** [comment]
Okay. Glad it works now for you. No need for further debugging. :)
You can close this issue if it is resolved.
