### ISSUE TITLE
Null pointer exception

### ISSUE THREAD

**Issue by cappah** [LWJGL/lwjgl3-demos#4]
Exception in thread "main" java.lang.NullPointerException
	at org.lwjgl.demo.opengl.util.DemoUtils.ioResourceToByteBuffer(DemoUtils.java:143)
	at org.lwjgl.demo.vulkan.ColoredTriangleDemo.loadShader(ColoredTriangleDemo.java:666)
	at org.lwjgl.demo.vulkan.ColoredTriangleDemo.loadShader(ColoredTriangleDemo.java:687)
	at org.lwjgl.demo.vulkan.ColoredTriangleDemo.createPipeline(ColoredTriangleDemo.java:884)
	at org.lwjgl.demo.vulkan.ColoredTriangleDemo.main(ColoredTriangleDemo.java:1186)

` public static ByteBuffer ioResourceToByteBuffer(String resource, int bufferSize) throws IOException {
        ByteBuffer buffer;
        URL url = Thread.currentThread().getContextClassLoader().getResource(resource);
        File file = new File(url.getFile()); // this line`

**Comment by httpdigest** [comment]
You need to have /res in your classpath.
