### ISSUE TITLE
Intel UHD cards crash

### ISSUE THREAD

**Issue by zebalu** [LWJGL/lwjgl3-demos#48]
Hi!

On Intel UHD cards the demo crashes, unless I set the `canGenerateDrawCallsViaShader` property to `false` ([here](https://github.com/LWJGL/lwjgl3-demos/blob/main/src/org/lwjgl/demo/game/VoxelGameGL.java#L1223)). The error message is:

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007fff5f0adbf7, pid=11684, tid=20596
#
# JRE version: OpenJDK Runtime Environment GraalVM CE 21.3.2 (11.0.15+10) (build 11.0.15+10-jvmci-21.3-b14)
# Java VM: OpenJDK 64-Bit Server VM GraalVM CE 21.3.2 (11.0.15+10-jvmci-21.3-b14, mixed mode, sharing, tiered, jvmci, jvmci compiler, compressed oops, g1 gc, windows-amd64)
# Problematic frame:
# C  [igxelpicd64.dll+0x22dbf7]
#
# No core dump will be written. Minidumps are not enabled by default on client versions of Windows
#
# An error report file with more information is saved as:
```

or with debug:

```
[LWJGL] Loading library: opengl32
[LWJGL]         Module: org.lwjgl.opengl
[LWJGL]         opengl32.dll not found in org.lwjgl.librarypath=C:\Users\[DELETED]\3.3.2-SNAPSHOT
[LWJGL]         Loaded from system paths: C:\Windows\SYSTEM32\opengl32.dll
[LWJGL] Failed to locate address for GL function glNamedFramebufferTextureMultiviewOVR
[LWJGL] [GL] GL_OVR_multiview was reported as available but an entry point is missing.
useMultiDrawIndirect: true
useBufferStorage: true
drawPointsWithGS: true
useInverseDepth: true
useNvMultisampleCoverage: false
canUseSynchronousDebugCallback: true
canGenerateDrawCallsViaShader: true
useOcclusionCulling: true
useTemporalCoherenceOcclusionCulling: true
canSourceIndirectDrawCallCountFromBuffer: true
useRepresentativeFragmentTest: false
uniformBufferOffsetAlignment: 16
[LWJGL] [GL] Using KHR_debug for error logging.
[LWJGL] OpenGL debug message
        ID: 0x0
        Source: SHADER COMPILER
        Type: ERROR
        Severity: HIGH
        Message: SHADER_ID_COMPILE error has been generated. GLSL compile failed for shader 9, "": ERROR: 0:8: 'writeonly' : reserved word
ERROR: 0:8: 'writeonly' : syntax error syntax error


ERROR: 0:8: 'writeonly' : reserved word
ERROR: 0:8: 'writeonly' : syntax error syntax error


Exception in thread "main" java.lang.AssertionError: Could not compile shader: org/lwjgl/demo/game/voxelgame/boundingboxes.vs.glsl
        at org.lwjgl.demo.game.VoxelGameGL.createShader(VoxelGameGL.java:1623)
        at org.lwjgl.demo.game.VoxelGameGL.createBoundingBoxesProgram(VoxelGameGL.java:1803)
        at org.lwjgl.demo.game.VoxelGameGL.initGLResources(VoxelGameGL.java:3528)
        at org.lwjgl.demo.game.VoxelGameGL.run(VoxelGameGL.java:3477)
        at org.lwjgl.demo.game.VoxelGameGL.main(VoxelGameGL.java:3542)
[LWJGL] 56 bytes leaked, thread 1 (main), address: 0x233648B0190
        at org.lwjgl.system.Callback.create(Callback.java:163)
        at org.lwjgl.system.CallbackI.address(CallbackI.java:25)
        at org.lwjgl.system.MemoryUtil.memAddressSafe(MemoryUtil.java:850)
        at org.lwjgl.glfw.GLFW.glfwSetFramebufferSizeCallback(GLFW.java:3345)
        at org.lwjgl.demo.game.VoxelGameGL.registerWindowCallbacks(VoxelGameGL.java:1132)
        at org.lwjgl.demo.game.VoxelGameGL.run(VoxelGameGL.java:3473)
        at org.lwjgl.demo.game.VoxelGameGL.main(VoxelGameGL.java:3542)
[LWJGL] 56 bytes leaked, thread 1 (main), address: 0x233648B0210
        at org.lwjgl.system.Callback.create(Callback.java:163)
        at org.lwjgl.system.CallbackI.address(CallbackI.java:25)
        at org.lwjgl.system.MemoryUtil.memAddressSafe(MemoryUtil.java:850)
        at org.lwjgl.glfw.GLFW.glfwSetCursorPosCallback(GLFW.java:4121)
        at org.lwjgl.demo.game.VoxelGameGL.registerWindowCallbacks(VoxelGameGL.java:1134)
        at org.lwjgl.demo.game.VoxelGameGL.run(VoxelGameGL.java:3473)
        at org.lwjgl.demo.game.VoxelGameGL.main(VoxelGameGL.java:3542)
[LWJGL] 56 bytes leaked, thread 1 (main), address: 0x233648B0290
        at org.lwjgl.system.Callback.create(Callback.java:163)
        at org.lwjgl.system.CallbackI.address(CallbackI.java:25)
        at org.lwjgl.opengl.GLDebugMessageCallback.create(GLDebugMessageCallback.java:54)
        at org.lwjgl.opengl.GLUtil.setupDebugMessageCallback(GLUtil.java:63)
        at org.lwjgl.opengl.GLUtil.setupDebugMessageCallback(GLUtil.java:30)
        at org.lwjgl.demo.game.VoxelGameGL.installDebugCallback(VoxelGameGL.java:1187)
        at org.lwjgl.demo.game.VoxelGameGL.initGLResources(VoxelGameGL.java:3512)
        at org.lwjgl.demo.game.VoxelGameGL.run(VoxelGameGL.java:3477)
        at org.lwjgl.demo.game.VoxelGameGL.main(VoxelGameGL.java:3542)
[LWJGL] 56 bytes leaked, thread 1 (main), address: 0x233648B01D0
        at org.lwjgl.system.Callback.create(Callback.java:163)
        at org.lwjgl.system.CallbackI.address(CallbackI.java:25)
        at org.lwjgl.system.MemoryUtil.memAddressSafe(MemoryUtil.java:850)
        at org.lwjgl.glfw.GLFW.glfwSetKeyCallback(GLFW.java:3985)
        at org.lwjgl.demo.game.VoxelGameGL.registerWindowCallbacks(VoxelGameGL.java:1133)
        at org.lwjgl.demo.game.VoxelGameGL.run(VoxelGameGL.java:3473)
        at org.lwjgl.demo.game.VoxelGameGL.main(VoxelGameGL.java:3542)
[LWJGL] 56 bytes leaked, thread 1 (main), address: 0x233648B0250
        at org.lwjgl.system.Callback.create(Callback.java:163)
        at org.lwjgl.system.CallbackI.address(CallbackI.java:25)
        at org.lwjgl.system.MemoryUtil.memAddressSafe(MemoryUtil.java:850)
        at org.lwjgl.glfw.GLFW.glfwSetMouseButtonCallback(GLFW.java:4091)
        at org.lwjgl.demo.game.VoxelGameGL.registerWindowCallbacks(VoxelGameGL.java:1135)
        at org.lwjgl.demo.game.VoxelGameGL.run(VoxelGameGL.java:3473)
        at org.lwjgl.demo.game.VoxelGameGL.main(VoxelGameGL.java:3542)
```

I accept if you don't change anything but it might worth a mention in the FAQ section, so others won't debug the same issue for as long as I have.

Thanks

**Comment by httpdigest** [comment]
Thanks for the info! Yeah, Nvidia drivers are apparently _a lot_ more lenient when it comes to using language features that are not _explicitly_ enabled in the shaders. I've updated the shader code with enabling the `GL_ARB_shader_image_load_store` extension (which is queried anyway before taking that code/render path) which brings the `writeonly` language feature.

**Comment by zebalu** [comment]
You are very cool man! I am still learning the OpenGL / 3D world and didn't even know about this workaround. I can confirm now, it is working; and running as smooth as on my Nvidia card. Please accept my gratitudes!
