### ISSUE TITLE
Some examples do not work

### ISSUE THREAD

**Issue by Ltutamen** [LWJGL/lwjgl3-demos#51]
When I try to run some examples (AtomicDemo, for example), I get exceptions like 
```	
Message: 0:0(0): error: Compute shaders require GLSL 4.30 or GLSL ES 3.10 
```
I managed to fix this issues myself with some trivial changes to the code, but I wonder, why am I getting such errors, is it a problem with my setup, or demo code needs some maintenance? I am running ubuntu 22 and use Intel uhd graphics for 10'th gen.

**Comment by httpdigest** [comment]
It would be good if you told which other demos you are referring to (other than AtomicDemo) with your "some examples" and what changes you needed to make ("I managed to fix this issues myself with some trivial changes to the code") in order to get those to run in your case, please.

**Comment by Ltutamen** [comment]
I've run all examples in `raytraycing` folder and got results like this - https://pastebin.com/YjAfcAYS
I run an example by changing glsl shader version to 430 in code and in randomAtomic.glslcs file

**Comment by Ltutamen** [comment]
I've run all examples in `raytraycing` folder and got results like this - https://pastebin.com/YjAfcAYS
I run an example by changing glsl shader version to 430 in code and in randomAtomic.glslcs file

**Comment by Desoroxxx** [comment]
The Vulkan RT examples are just broken for me
````
PS D:\GitHub\lwjgl3-demos> java -cp target/lwjgl3-demos.jar org.lwjgl.demo.vulkan.raytracing.SdfBricks
[LWJGL] Version: 3.3.3-snapshot
         OS: Windows 11 v10.0
        JRE: Windows amd64 21
        JVM: OpenJDK 64-Bit Server VM v21+35-LTS by Eclipse Adoptium
[LWJGL] Loading JNI library: lwjgl
        Module: org.lwjgl
        Using SharedLibraryLoader...
        Found at: C:\Users\desor\AppData\Local\Temp\lwjgl_desor\3.3.3-snapshot\x64\lwjgl.dll
        Loaded from org.lwjgl.librarypath: C:\Users\desor\AppData\Local\Temp\lwjgl_desor\3.3.3-snapshot\x64\lwjgl.dll
[LWJGL] Loading library: glfw
        Module: org.lwjgl.glfw
        Using SharedLibraryLoader...
        Found at: C:\Users\desor\AppData\Local\Temp\lwjgl_desor\3.3.3-snapshot\x64\glfw.dll
        Loaded from org.lwjgl.librarypath: C:\Users\desor\AppData\Local\Temp\lwjgl_desor\3.3.3-snapshot\x64\glfw.dll
[LWJGL] Loading library: vulkan-1
        Module: org.lwjgl.vulkan
        vulkan-1.dll not found in org.lwjgl.librarypath=C:\Users\desor\AppData\Local\Temp\lwjgl_desor\3.3.3-snapshot\x64
[LWJGL] Loading library: jemalloc
        Module: org.lwjgl.jemalloc
        Using SharedLibraryLoader...
        Found at: C:\Users\desor\AppData\Local\Temp\lwjgl_desor\3.3.3-snapshot\x64\jemalloc.dll
        Loaded from org.lwjgl.librarypath: C:\Users\desor\AppData\Local\Temp\lwjgl_desor\3.3.3-snapshot\x64\jemalloc.dll
[LWJGL] Closure Registry: simple
[LWJGL] MemoryUtil allocator: DebugAllocator
        Loaded from system paths: C:\WINDOWS\SYSTEM32\vulkan-1.dll
[LWJGL] Loading JNI library: lwjgl_vma
        Module: org.lwjgl.vma
        Using SharedLibraryLoader...
        Found at: C:\Users\desor\AppData\Local\Temp\lwjgl_desor\3.3.3-snapshot\x64\lwjgl_vma.dll
        Loaded from org.lwjgl.librarypath: C:\Users\desor\AppData\Local\Temp\lwjgl_desor\3.3.3-snapshot\x64\lwjgl_vma.dll
Exception in thread "main" java.lang.AssertionError: Illegal address alignment
        at org.lwjgl.demo.vulkan.raytracing.SdfBricks.bufferAddress(SdfBricks.java:1054)
        at org.lwjgl.demo.vulkan.raytracing.SdfBricks.deviceAddress(SdfBricks.java:1037)
        at org.lwjgl.demo.vulkan.raytracing.SdfBricks.createBottomLevelAccelerationStructure(SdfBricks.java:1131)
        at org.lwjgl.demo.vulkan.raytracing.SdfBricks.init(SdfBricks.java:1686)
        at org.lwjgl.demo.vulkan.raytracing.SdfBricks.main(SdfBricks.java:1760)
[LWJGL] 56 bytes leaked, thread 1 (main), address: 0x1DE678D01D0
[LWJGL] 56 bytes leaked, thread 1 (main), address: 0x1DE678D0250
[LWJGL] 208 bytes leaked, thread 1 (main), address: 0x1DE723000E0
[LWJGL] 208 bytes leaked, thread 1 (main), address: 0x1DE72300460
[LWJGL] 90112 bytes leaked, thread 1 (main), address: 0x1DEAACE0C80
[LWJGL] 64 bytes leaked, thread 1 (main), address: 0x1DEAACD0000
[LWJGL] 4392 bytes leaked, thread 1 (main), address: 0x1DEAACA0000
[LWJGL] 4392 bytes leaked, thread 1 (main), address: 0x1DEAACA1400
[LWJGL] 768 bytes leaked, thread 1 (main), address: 0x1DEAAC80000
[LWJGL] 768 bytes leaked, thread 1 (main), address: 0x1DEAAC80300
[LWJGL] 128 bytes leaked, thread 1 (main), address: 0x1DEAAC90000
[LWJGL] 128 bytes leaked, thread 1 (main), address: 0x1DEAAC90080
[LWJGL] 128 bytes leaked, thread 1 (main), address: 0x1DEAAC90100
[LWJGL] 136 bytes leaked, thread 1 (main), address: 0x1DEAAC60000
[LWJGL] 400 bytes leaked, thread 1 (main), address: 0x1DEAAC70000
[LWJGL] 208 bytes leaked, thread 1 (main), address: 0x1DE723001C0
[LWJGL] 208 bytes leaked, thread 1 (main), address: 0x1DE72300540
[LWJGL] 136 bytes leaked, thread 1 (main), address: 0x1DEAAC600A0
[LWJGL] 56 bytes leaked, thread 1 (main), address: 0x1DE678D0190
[LWJGL] 56 bytes leaked, thread 1 (main), address: 0x1DE678D0210
[LWJGL] 208 bytes leaked, thread 1 (main), address: 0x1DE723002A0
[LWJGL] 208 bytes leaked, thread 1 (main), address: 0x1DE72300620
[LWJGL] 64 bytes leaked, thread 1 (main), address: 0x1DEAACD0040
[LWJGL] 400 bytes leaked, thread 1 (main), address: 0x1DEAAC701C0
[LWJGL] 208 bytes leaked, thread 1 (main), address: 0x1DE72300000
[LWJGL] 208 bytes leaked, thread 1 (main), address: 0x1DE72300380
[LWJGL] 6776 bytes leaked, thread 1 (main), address: 0x1DE722D0000
[LWJGL] Reminder: disable Configuration.DEBUG_MEMORY_ALLOCATOR_FAST to get stacktraces of leaking allocations.
```

**Comment by goofyseeker311** [comment]
my test results running the demos so far:

any of the demo.bgfx does not work:
Exception in thread "main" java.lang.RuntimeException: Error initializing bgfx renderer
	at org.lwjgl.demo.bgfx.Demo.run(Demo.java:128)
	at org.lwjgl.demo.bgfx.Metaballs.main(Metaballs.java:359)

demo.opengl.raytracing Demo33 does not work:
0(9) : error C7532: global type uvec3 requires "#version 130" or later
0(9) : error C0000: ... or #extension GL_EXT_gpu_shader4 : enable
0(14) : error C7548: '>>' requires "#extension GL_EXT_gpu_shader4 : enable" before use
0(21) : error C7532: global function floatBitsToUint requires "#version 330" or later
0(21) : error C0000: ... or #extension GL_ARB_shader_bit_encoding : enable
0(21) : error C0000: ... or #extension GL_ARB_gpu_shader5 : enable
0(21) : error C7548: '&' requires "#extension GL_EXT_gpu_shader4 : enable" before use
0(21) : error C7548: '|' requires "#extension GL_EXT_gpu_shader4 : enable" before use
0(21) : error C7532: global function uintBitsToFloat requires "#version 330" or later
0(21) : error C0000: ... or #extension GL_ARB_shader_bit_encoding : enable
0(21) : error C0000: ... or #extension GL_ARB_gpu_shader5 : enable
java.lang.AssertionError: Could not compile shader
	at org.lwjgl.demo.opengl.util.DemoUtils.createShader(DemoUtils.java:164)
	at org.lwjgl.demo.opengl.util.DemoUtils.createShader(DemoUtils.java:112)
	at org.lwjgl.demo.opengl.raytracing.Demo33.createRayTracingProgram(Demo33.java:258)
	at org.lwjgl.demo.opengl.raytracing.Demo33.init(Demo33.java:214)
	at org.lwjgl.demo.opengl.raytracing.Demo33.run(Demo33.java:455)
	at org.lwjgl.demo.opengl.raytracing.Demo33.main(Demo33.java:475)

**Comment by ThanosFisherman** [comment]
Same here I couldn't run any of the vulkan raytracing samples. Keep getting similar errors
